# This workflow runs on 'pull_request_target' so that PRs from forks are able
# to run an action that uses the SEMGREP_APP_TOKEN secret
# Note that any modification of this file in a PR does not reflect on said PR
# Changes must be merged to develop first
name: semgrep
on:
  workflow_dispatch:
  pull_request:

jobs:
  semgrep-run-app-config:
    name: semgrep with app connection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: '0'
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: "1"

  semgrep-run-local-config:
    name: semgrep with local config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: '0'
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        env:
          SEMGREP_RULES: semgrep.yml
