name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to validate"
        required: true
        type: string

jobs:
  validate-release-trigger:
    name: Trigger Release Validation
    uses: ./.github/workflows/validate-release.yml
    secrets: inherit
    with:
      version: ${{inputs.version}}
