# Validate a Release
name: validate-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version to validate"
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  sanity_check_release:
    name: Sanity check the release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.version }}"
      - name: Validate the release
        run: ./scripts/validate-release.py ${{ inputs.version }}

  verify_docker_release:
    name: Verify the docker release works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.version }}"
      - name: Validate docker release
        run: ./scripts/validate-docker-release.sh ${{ inputs.version }}

  verify_ubuntu_release:
    name: Verify the ubuntu release works
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "v${{ inputs.version }}"
      - name: build tester image
        uses: docker/build-push-action@v3
        with:
          push: false
          path: scripts
          dockerfile: scripts/Dockerfile.16.04
          build_args: version=${{ inputs.version }}
